### PR TITLE
Update .gitmodules

### PR DESCRIPTION
**Pull request by SwissalpS**
adopting cheapie's mods as they are no longer interested in maintaining minetest mods

Q: is there something more that needs to be done apart from changing ``.gitmodules`` file?
I don't often deal with gitmodules and something tells me this wasn't all.

### CODE REVIEW

**Comment by wsor4035** [comment]
see https://github.com/mt-mods/dreambuilder_game/pull/337

**Comment by wsor4035** [comment]
forcing a rerun of the tests, not sure why there are failing/not running, possibly because this was before https://github.com/mt-mods/dreambuilder_game/commit/59406bf4c6f137bc751d864465adf5ebdc9cd694 ?

**Review by wsor4035 — CHANGES_REQUESTED** [review]
image

please switch to `https://github.com/mt-mods/invsaw/`

**Comment by SwissalpS** [comment]
> image
> 
> please switch to `https://github.com/mt-mods/invsaw/`

I'd prefer merging this after #527 is merged, then we can add some others too.

**Comment by SwissalpS** [comment]
> forcing a rerun of the tests, not sure why there are failing/not running, possibly because this was before [59406bf](https://github.com/mt-mods/dreambuilder_game/commit/59406bf4c6f137bc751d864465adf5ebdc9cd694) ?

In #527 I pulled in changes from master and tests still fail.

**Comment by wsor4035** [comment]
> > forcing a rerun of the tests, not sure why there are failing/not running, possibly because this was before [59406bf](https://github.com/mt-mods/dreambuilder_game/commit/59406bf4c6f137bc751d864465adf5ebdc9cd694) ?
> 
> In #527 I pulled in changes from master and tests still fail.

reading the next issue points out the actual issue with the tests: <https://github.com/mt-mods/dreambuilder_game/pull/576#pullrequestreview-1938003728>

**Comment by BuckarooBanzay** [comment]
> the tests are failing since frankly @BuckarooBanzay broke dreambuilder by deleting the repos before they where removed as submodules from other projects. further more it might have been better to just transfer those repos over to mt-mods, so that github did redirects and not a clean break

oh sh... sorry, forgot about that :/

**Pull request merged**
