### PR TITLE
change minetest engine docker location + add new versions of mte

### PR DESCRIPTION
**Pull request by wsor4035**
what the title says

### CODE REVIEW

**Comment by wsor4035** [comment]
current status, it works. have asked buckaroo on discord about getting older versions at https://github.com/minetest-hosting/minetest-docker/pkgs/container/minetest-docker/versions?filters%5Bversion_type%5D=tagged

**Comment by BuckarooBanzay** [comment]
i implemented the testing with old and new image locations in my wip game here: https://github.com/BuckarooBanzay/eco/blob/8da3b2d1be646d5231b7c4047afacfd929ecbd0b/.github/workflows/test.yml#L11-L16
do you mind if i alter your PR?

**Comment by wsor4035** [comment]
> i implemented the testing with old and new image locations in my wip game here: https://github.com/BuckarooBanzay/eco/blob/8da3b2d1be646d5231b7c4047afacfd929ecbd0b/.github/workflows/test.yml#L11-L16 do you mind if i alter your PR?

sure, probably best as you originally implemented this

**Comment by BuckarooBanzay** [comment]
> sure, probably best as you originally implemented this

done :+1:

**Review by wsor4035 — COMMENTED** [review]
cant approve my own pr, but looks good, thanks

**Pull request merged**
