### PR TITLE
Is ground content revision

### PR DESCRIPTION
**Pull request by SwissalpS**
see https://github.com/pandorabox-io/pandorabox.io/issues/836

also some whitespace indent fixes

### CODE REVIEW

**Comment by wsor4035** [comment]
seems at least some of these really should have there upstream added in here as a submodule

**Comment by SwissalpS** [comment]
> seems at least some of these really should have there upstream added in here as a submodule

I agree in general. Just don't see that as in the scope of this revision.

**Comment by wsor4035** [comment]
> > seems at least some of these really should have there upstream added in here as a submodule
> 
> I agree in general. Just don't see that as in the scope of this revision.

it just means that the "bugs" will come back when switching to the proper submodules unless you are also pring these changes upstream

**Comment by SwissalpS** [comment]
yes, depending on which fork is upstream, I may have already PRed them ;)

**Comment by SwissalpS** [comment]
@wsor4035 can we merge this to avoid conflicts when submoduling [jumping] and maybe others?

**Comment by Niklp09** [comment]
@SwissalpS Rebase required.

**Comment by SwissalpS** [comment]
> @SwissalpS Rebase required.

no kidding. This mess could've been avoided ...

**Review by Niklp09 — CHANGES_REQUESTED** [review]
- ground_contest stuff looks good :+1: 
- PR auto-merge stuff should(?) be removed from this PR
- Not sure what this is
image

**Comment by SwissalpS** [comment]
> * Not sure what this is

If only this PR had been merged before moving mods to modules, this mess could've been avoided.

I've force pushed the changes that matter. I hope nothing slipped through.

**Review by Niklp09 — APPROVED** [review]
LGTM
I apologize that this one took so long

**Comment by SwissalpS** [comment]
> LGTM I apologize that this one took so long

no problem, wasn't your fault :D

**Pull request merged**
